# Generated by Django 2.1.9 on 2019-07-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileData',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('SmartPhone_OS', models.CharField(max_length=200)),
                ('Img_Path', models.CharField(max_length=300)),
                ('ScreenResolution', models.CharField(max_length=200)),
                ('ScreenSize', models.CharField(max_length=100)),
                ('Processor', models.CharField(max_length=100)),
                ('GPU', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=100)),
            ],
        ),
    ]
