# Generated by Django 2.1.9 on 2019-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
